name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Trivy
        run: |
          curl -sfL https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.33.0_Linux-64bit.deb -o trivy.deb
          sudo dpkg -i trivy.deb
          sudo apt-get install -f
          trivy --version  # Sprawdzanie, czy Trivy zostało poprawnie zainstalowane

      - name: Run tests (placeholder)
        run: echo "Test"

      - name: Build Docker image
        run: docker build -t devops-app .
